Feat standarize ctrl
Fillikenes/webscraping-firebase-api pull request #19
Opened 2023-01-21 01:03 UTC by NicolasHCastillo

# ¿QUE?
Se modifico las respuestas para las funciones get y search del modulo de TuMangas

# ¿Como?
haciendo uso de las interfaces de IBaseController,  IOutboundChapter,  IOutboundSearchResponse con la finalidad de dejar dichas respuestas estandarizadas

2023-01-29 00:38 UTC, chelosky commented on src/modules/in-manga/in-manga.controller.ts
> +  IOutboundChapter,
no se usa esta dependencia

2023-01-29 00:39 UTC, chelosky commented on src/modules/in-manga/in-manga.controller.ts
> +  IOutboundSearchResponse,
no se usa esta dependencia

2023-01-29 00:39 UTC, chelosky commented on src/modules/in-manga/mocks/index.ts
> +import { IOutboundChapter, IOutboundImage } from '../../../interfaces';
no se usa esta dependencia

2023-01-29 00:40 UTC, chelosky commented on src/modules/tu-mangas/tu-mangas.service.spec.ts
> +      // innerHTML: {
elimina los comentarios

2023-01-29 00:40 UTC, chelosky commented on src/modules/tu-mangas/tu-mangas.service.ts
> +        const chapter = el.children[0].innerHTML;
cambia el nombre de la variable a chapterName o name directamente

2023-01-29 00:41 UTC, chelosky requested changes
Revisar comentarios plz

2023-01-29 00:47 UTC, NicolasHCastillo commented on src/modules/in-manga/in-manga.controller.ts
> +  IOutboundSearchResponse,
pero ese modulo es el que ya no usaremos

2023-01-29 01:29 UTC, chelosky commented on src/modules/in-manga/in-manga.controller.ts
> +  IOutboundSearchResponse,
por eso mismo, no deberia estar importada en el archivo, no se esta usando

2023-01-29 01:32 UTC, NicolasHCastillo commented on src/modules/in-manga/in-manga.controller.ts
> +  IOutboundSearchResponse,
vale entonces lo borro

2023-04-27 21:45 UTC, chelosky approved these changes

2023-04-28 03:38 UTC, merged